### ISSUE TITLE
Implementation of DoubleColoredMNIST

### ISSUE THREAD

**Issue by gessha** [autonomousvision/counterfactual_generative_networks#2]
Hi! 

Thank you so much for posting your code online! I was really fascinated by your work and I presented it recently at the computer vision seminar at Stony Brook University. 

I was tinkering with the implementation of DoubleColoredMNIST because I want to use it in a related project and I noticed something strange: In the class implementation, colors are assigned to global tensors and every time an image is requested, the global color tensors get jittered instead of jittering a local copy. Is this the intended implementation or is this something unintended?

Reproduction code:
``` Python
ds = DoubleColoredMNIST(train=True)

print(ds.background_colors[5].view(1, 3), ds.object_colors[5].view(1, 3))
# -> tensor([[0.8706, 0.7216, 0.5294]]) tensor([[0.3922, 0.5843, 0.9294]])

first_image = ds[0]
image, label = first_image['ims'], first_image['labels']

print(ds.background_colors[5].view(1, 3), ds.object_colors[5].view(1, 3))
# -> tensor([[0.8725, 0.7374, 0.5306]]) tensor([[0.3945, 0.5922, 0.9359]])
```

If you can notice, the tensors between the two calls get changed. 

This issue comes from line 87 and line 91 in `mnists/dataloader.py` where I assume the intended action is to copy the color tensor. What happens instead is the local variables `back_color` and `obj_color` refer to the global color tensors and they get jittered instead. 

``` Python
# line 87:
back_color = self.background_colors[i]
...

# line 91:
obj_color = self.object_colors[i]
```
If you add `.clone()` to the end of assignment, you will avoid this problem. 

``` Python
# line 87:
back_color = self.background_colors[i].clone()
```

Let me know if this is actually a bug or feature of the implementation 😅

**Comment by xl-sr** [comment]
hey, thanks for your question and good catch! Somehow this clone got lost, it used to be there ... It should not change the end results, but jittering it locally is the intended behavior. The code is updated, thanks for spotting this bug :)
